name: pixi
on: [push, pull_request]
jobs:
  pixi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
      - name: lint
        run: pixi run ruff
      - name: ty
        run: pixi run ty
      - name: test
        run: pixi run test