name: pixi
on: [push, pull_request]
jobs:
  pixi:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        task: [ruff, ty, test, doc]
    steps:
      - uses: actions/checkout@v6
      - name: Set up Pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          cache: true
      - name: run task
        run: pixi run ${{ matrix.task }}